---
- hosts: localhost
  connection: local
  vars:
    ansible_become_password: "{{ lookup('env', 'SUDO_PASSWORD') }}"
  pre_tasks:
    - name: Detect WSL
      ansible.builtin.import_tasks: tasks/detect_wsl.yml
      # tags:
      #   - always

    - name: Detect wsl
      ansible.builtin.debug:
        var: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Confirm Windows PowerShell Execution Policy
      ansible.builtin.import_tasks: tasks/powershell_executionpolicy.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: tasks/whoami_wsl.yml
      when: ansible_host_environment_is_wsl
      tags:
        - always

    - name: Detect Host User
      ansible.builtin.import_tasks: tasks/whoami.yml
      tags:
        - always

    - name: Display the current user
      debug:
        msg: "Current user is {{ host_user }}"        
    - name: Display the ssh user
      debug:
        msg: "Current ssh user is {{ ansible_user_id }}"        

  tasks:                      
    - name: Set Cronjobs
      include_tasks: tasks/cronjob.yml
    - name: Ensure ~/.local/bin exists
      file:
        path: ~/.local/bin
        state: directory
        mode: '0755'

    - name: Install ripgrep
      unarchive:
        src: "https://github.com/BurntSushi/ripgrep/releases/download/14.1.0/ripgrep-14.1.0-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
        dest: ~/.local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: ~/.local/bin/rg

    - name: Install assh
      unarchive:
        src: "https://github.com/moul/assh/releases/download/v2.16.0/assh_2.16.0_linux_amd64.tar.gz"
        dest: ~/.local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: ~/.local/bin/assh

    - name: Install bat
      unarchive:
        src: "https://github.com/sharkdp/bat/releases/download/v0.24.0/bat-v0.24.0-i686-unknown-linux-musl.tar.gz"
        dest: ~/.local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: ~/.local/bin/bat

    - name: Install delta
      unarchive:
        src: "https://github.com/dandavison/delta/releases/download/0.17.0/delta-0.17.0-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
        dest: ~/.local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: ~/.local/bin/delta

    - name: Install eza
      unarchive:
        src: "https://github.com/eza-community/eza/releases/latest/download/eza_{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
        dest: ~/.local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: ~/.local/bin/eza

    - name: Install zoxide
      unarchive:
        src: "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.4/zoxide-0.9.4-{{ ansible_architecture }}-unknown-linux-musl.tar.gz"
        dest: ~/.local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: ~/.local/bin/zoxide

    - name: Install sesh
      unarchive:
        src: "https://github.com/joshmedeski/sesh/releases/download/v2.1.2/sesh_Linux_x86_64.tar.gz"
        dest: ~/.local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: ~/.local/bin/sesh

    - name: Install yq
      unarchive:
        src: "https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64.tar.gz"
        dest: ~/.local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: ~/.local/bin/yq
        
    - name: Rename yq executable
      command: mv ~/.local/bin/yq_linux_amd64 ~/.local/bin/yq
      args:
        removes: ~/.local/bin/yq
      when: ansible_os_family == "Linux"
    
    - name: Create symlink for jq
      file:
        src: ~/.local/bin/yq
        dest: ~/.local/bin/jq
        state: link
        
    - name: Install teller
      unarchive:
        src: "https://github.com/tellerops/teller/releases/download/v2.0.7/teller-{{ ansible_architecture }}-linux.tar.xz"
        dest: ~/.local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: ~/.local/bin/teller

    - name: Install pkgx
      unarchive:
        src: "https://pkgx.sh/{{ ansible_os_family | lower }}/{{ ansible_architecture }}.tgz"
        dest: ~/.local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: ~/.local/bin/pkgx

    - name: Install ctop
      get_url:
        url: "https://github.com/bcicen/ctop/releases/download/v0.7.7/ctop-0.7.7-linux-amd64"
        dest: ~/.local/bin/ctop
        mode: '0755'
        
    - name: setup atuin
      unarchive:
        src: "https://github.com/atuinsh/atuin/releases/download/v18.3.0/atuin-x86_64-unknown-linux-musl.tar.gz"
        dest: ~/.atuin/bin/atuin
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: ~/.atuin/bin/atuin    
      
