- name: install packages
  become: true
  package:
    name:
      - ansible
      - autossh      
      - curl
      - feh      
      - git 
      - git-crypt 
      - gpg 
      - gpg-agent 
      - htop
      - lolcat 
      - neofetch
      - ncdu
      - mc 
      - myrepos 
      - python3-watchdog
      - sshuttle
      - tldr
      - unzip
      - vim
      - vcsh
      - wget 
      - zip
      
 
