- name: install packages
  become: true
  package:
    name:
      - ansible
      - autossh      
      - curl
      - feh      
      - git 
      - git-crypt 
      - gpg 
      - gpg-agent 
      - htop
      - lolcat 
      - neofetch
      - ncdu
      - mc 
      - myrepos 
      - python3-watchdog
      - sshuttle
      - tldr
      - unzip
      - vim
      - vcsh
      - wget 
      - xkbset
      - zip
- name: Get Starship install script
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '0755'

- name: Install Starship
  become: true
  shell: /tmp/starship_install.sh --yes
  args:
    executable: /bin/sh 

