- name: Set timezone to Asia/Tehran
  become: yes
  copy:
    content: "Asia/Tehran"
    dest: /etc/timezone
    owner: root
    group: root
    mode: '0644'
  register: timezone

- name: Reconfigure Timezone Data (if changed)
  become: yes
  shell: dpkg-reconfigure -f noninteractive tzdata
  when: timezone.changed
