# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ~/.config/starship.toml
#
# ### Variant 2: two line prompt, no background in top line, separators on left side
# *** Borrowed from a design seen in a zsh (should be from https://github.com/romkatv/powerlevel10k)
#
# - No filling solid line in top row: 
#   Replace '$fill\' with just one character '\' or just completely delete the line that contains '$fill\' further down,
#   within the format-block: format = """ ... """.
#
# - '$line_break': everything from the next line on refers to the second line of the prompt.
#
# - Some modules listed further down will not show up (all the time), as their default value is 'disabled = true' or
#   they are only displayed under certain conditions.
#
# - Symbols:
#   Don't be confused if you see this toml file via web browser on a website, gist, ... and you don't see any "real" symbols further down.
#   If Nerd-fonts are already installed on your system (e.g. MesloLG Nerd Font, FiraCode Nerd Font, ...) it should work.


# Customizing the prompt (and placing desired modules at desired position and sequence):
format = """
[╭╴](fg:#505050)\
$os\
$username\
$hostname\
$sudo\
$env_var\
$custom\
$shell\
$package\
$container\
$shlvl\
$singularity\
$kubernetes\
$fossil_branch\
$pijul_channel\
$docker_context\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$directory\
$vcsh\
${custom.git_server}$git_branch$git_commit$git_state$git_metrics$git_status\
$jobs\
$memory_usage\
[ ](fg:#242424)\
$cmd_duration\
$fill\
$line_break\
[╰╴](fg:#505050)\
[$status\
$battery\
$time\
$localip\
$character]($style)
"""

#$SOFTWARE_UPDATE_AVAILABLE\

# Inserts a blank line between shell prompts:
add_newline = true

# Customization and activation of some modules:
# Listed in the order of their position in the module row above
[os]
format = "[$symbol ]($style)[ ]()"
style = "fg:#AAAAAA"
disabled = false

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
CentOS = ""
Debian = ""
DragonFly = "🐉" # ""
Emscripten = "🔗"
EndeavourOS = "" # ""
Fedora = ""
FreeBSD = ""
Garuda = ""
Gentoo = ""
HardenedBSD = "聯"
Illumos = "🐦"
Linux = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = "🌘"
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = "" # ""
OpenCloudOS = "☁️"
openEuler = ""
openSUSE = ""
OracleLinux = "⊂⊃"
Pop = "" # ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
Redox = "🧪"
Solus = "" # " "
SUSE = ""
Ubuntu = ""
Unknown = ""
Windows = ""

[username]
format = '[ ](fg:green bold)[$user]($style)[ ]()'
style_user = 'fg:green bold'
style_root = 'fg:red bold'
show_always = false
disabled = false

[hostname]
format = '[$ssh_symbol ](fg:green bold)[$hostname](fg:green bold)[ ]()'
ssh_only = true
ssh_symbol = '' # '⇒' # ' ' # 'ﬁ⇒'
#trim_at = '.companyname.com'
disabled = false

[sudo]
format = '[ ](fg:red bold)[as $symbol]($style)'
style = 'fg:red bold'
symbol = ' ' # ' ❯ '
disabled = false

[shell]
disabled = false
format = '[ ]($style)[$indicator]($style)' #(fg:#ad4007)
style = 'fg:cyan bold'
fish_indicator = "󰈺 "
bash_indicator = " "
powershell_indicator = " "
xonsh_indicator = " "
zsh_indicator = " "  # You can choose any symbol you prefer

[env_var.SOFTWARE_UPDATE_AVAILABLE]
variable = 'SOFTWARE_UPDATE_AVAILABLE'
format = '[ ]($style)[$env_value]($style)'
default = ''
symbol = '📦 '
style = 'bold cyan'

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 30
style = "bold red"

[directory]
format = '[ ](fg:cyan bold)[$read_only]($read_only_style)[$repo_root]($repo_root_style)[ $path]($style)'
style = 'fg:cyan bold'
home_symbol = ' ~'
read_only = ' ' # ' ' # ' ''
read_only_style = 'fg:cyan'
truncation_length = 3
truncation_symbol = '…/'
truncate_to_repo = true
# repo_root_format = '[ ](fg:cyan bold)[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[ ]()'
repo_root_format = '[ ](fg:cyan bold)[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[ ]()'
repo_root_style	= 'fg:cyan bold'
use_os_path_sep = true
disabled = false

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[custom.git_server]
#disabled = true
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
style = "white"
format = '[$output]($style) '

[git_branch]
format = '[❯ $symbol $branch(:$remote_branch)]($style)[ ]()'
style = 'fg:#E04D27'
symbol = ''
#ignore_branches = ['master', 'main']

[git_commit]
format = '[\($hash$tag\)]($style)[ ]()'
style = 'fg:#E04D27'
commit_hash_length = 8
tag_symbol = ' ' # ' ''
disabled = false

[git_metrics]
format = '[\[+$added/]($added_style)[-$deleted\]]($deleted_style)[ ]()'
added_style = 'fg:#E04D27'
deleted_style = 'fg:#E04D27'
disabled = false

[git_status]
# place symbols before '$count'
format = '([$all_status$ahead_behind]($style))'
style = 'fg:#E04D27'
conflicted = '[${count} ](fg:red)'
ahead = '[⇡${count} ](fg:yellow)'
behind = '[⇣${count} ](fg:yellow)'
diverged = '[⇕${ahead_count}⇡${behind_count}⇣ ](fg:yellow)' # ⇕ ↕ ⇳ 󰹹 󰹺 󰧈 
up_to_date = '[✓ ](fg:green)'
untracked = '[ﳇ${count} ](fg:red)' # ' ' # '? '
stashed = '[${count} ](fg:#A52A2A)' # '📦 '# ' ' # ' ' # ' ' # ' ' 
modified = '[󰷉${count} ](fg:#C8AC00)' # '📝' # '! ' #  #  # 
staged = '[${count} ](fg:green)' # '+ '
renamed = '[${count} ](fg:yellow)' # ' ' # '﫦' # ᴂ #  #  #  # ﳳ
deleted = '[﯊${count} ](fg:orange)' # '🗑 ' '- '
disabled = false

[jobs]
format = '[  ](fg:blue bold)[$number$symbol]($style)'
style = 'fg:blue'
symbol = '省' # '廒' # '󰜎' # '' # '✦'
symbol_threshold = 1
number_threshold = 4
disabled = false

[memory_usage]
format = '[  ](fg:purple bold)[$symbol ${ram} ${swap}]($style)'
style = 'fg:purple'
symbol = '﬙ 北' # '﬙ 痢' # '﬙ / 󰾵' # '󰍛 󰾵' # '﬙ 󰾴' # '﬙ 󰾶' # '﬙ 󰾷' '﬙ 󰣂'
threshold = 75
disabled = false

[cmd_duration]
format = '[ ⏱ $duration ]($style)'
style = 'fg:yellow'
min_time = 500
disabled = false

[time]
time_format = "%T"
format = "🕙 $time($style) "
style = "bright-white"
disabled = false

[fill]
style = 'fg:#505050'
symbol = '─'

[status]
format = '[$symbol$status $hex_status  $signal_number-$signal_name ]($style)'
style = 'fg:red'
symbol = '✘ '
disabled = false

[localip]
format = '[$localipv4 ](fg:green bold)'
ssh_only = true
disabled = false

[vcsh]
symbol = ''
#ignore_branches = ['master', 'main']
# style = "bold yellow"
style = 'bold yellow'
format = "vcsh [$symbol $repo]($style) "
# format = '[🆅 $repo](bold blue) '
disabled = false

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = '󰅟 '
style = "yellow"

[bun]
format = '\[[$symbol($version)]($style)\]'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol($version)]($style)\]'

[cobol]
format = '\[[$symbol($version)]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'

[crystal]
format = '\[[$symbol($version)]($style)\]'

[daml]
format = '\[[$symbol($version)]($style)\]'

[dart]
format = '\[[$symbol($version)]($style)\]'

[deno]
format = '\[[$symbol($version)]($style)\]'

[docker_context]
disabled = false
format = '\[[$symbol$context]($style)\]'

[dotnet]
format = '\[[$symbol($version)(🎯 $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[$symbol($version)]($style)\]'

[erlang]
format = '\[[$symbol($version)]($style)\]'

[fennel]
format = '\[[$symbol($version)]($style)\]'

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[golang]
format = '\[[$symbol($version)]($style)\]'

[gradle]
format = '\[[$symbol($version)]($style)\]'

[guix_shell]
format = '\[[$symbol]($style)\]'

[haskell]
format = '\[[$symbol($version)]($style)\]'

[haxe]
format = '\[[$symbol($version)]($style)\]'

[helm]
format = '\[[$symbol($version)]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[java]
format = '\[[$symbol($version)]($style)\]'

[julia]
format = '\[[$symbol($version)]($style)\]'

[kotlin]
format = '\[[$symbol($version)]($style)\]'

[kubernetes]
symbol = "☸️  "
style = "green"
disabled = false
format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol($version)]($style)\]'

[meson]
format = '\[[$symbol$project]($style)\]'

[nim]
format = '\[[$symbol($version)]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol($version)]($style)\]'

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
format = '\[[$symbol($version)]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[perl]
format = '\[[$symbol($version)]($style)\]'

[php]
format = '\[[$symbol($version)]($style)\]'

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = ' '
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'
style = "bold green"

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol($version)]($style)\]'

[ruby]
format = '\[[$symbol($version)]($style)\]'

[rust]
format = '\[[$symbol($version)]($style)\]'
style = "bold green"

[scala]
format = '\[[$symbol($version)]($style)\]'

[spack]
format = '\[[$symbol$environment]($style)\]'

[swift]
format = '\[[$symbol($version)]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[vagrant]
format = '\[[$symbol($version)]($style)\]'

[vlang]
format = '\[[$symbol($version)]($style)\]'

[zig]
format = '\[[$symbol($version)]($style)\]'
